# flake8: noqa

"""create cyptos models

Revision ID: 09573a8f5cee
Revises: 
Create Date: 2025-09-01 11:35:16.161525

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09573a8f5cee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("crypto_code", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crypto_code"),
    )
    op.create_index(op.f("ix_crypto_currency_id"), "crypto_currency", ["id"], unique=False)
    op.create_table(
        "crypto_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["currency_id"], ["crypto_currency.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crypto_price_id"), "crypto_price", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crypto_price_id"), table_name="crypto_price")
    op.drop_table("crypto_price")
    op.drop_index(op.f("ix_crypto_currency_id"), table_name="crypto_currency")
    op.drop_table("crypto_currency")
    # ### end Alembic commands ###
