"""update PeriodicTask+Crytpo  model

Revision ID: 253bca75f18f
Revises: ffa002896004
Create Date: 2025-09-03 21:27:51.340591

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "253bca75f18f"
down_revision: Union[str, Sequence[str], None] = "ffa002896004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crypto_currency", sa.Column("periodic_task_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "crypto_currency", "periodic_task", ["periodic_task_id"], ["id"])
    op.add_column("periodic_task", sa.Column("task_name", sa.String(length=255), nullable=False))
    op.add_column("periodic_task", sa.Column("task_params", sa.JSON(), nullable=True))
    op.add_column("periodic_task", sa.Column("task_queue", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("periodic_task", "task_queue")
    op.drop_column("periodic_task", "task_params")
    op.drop_column("periodic_task", "task_name")
    op.drop_constraint(None, "crypto_currency", type_="foreignkey")
    op.drop_column("crypto_currency", "periodic_task_id")
    # ### end Alembic commands ###
