"""periodic task model

Revision ID: ffa002896004
Revises: 09573a8f5cee
Create Date: 2025-09-03 20:23:35.764831

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa002896004"
down_revision: Union[str, Sequence[str], None] = "09573a8f5cee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "periodic_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_periodic_task_id"), "periodic_task", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_periodic_task_id"), table_name="periodic_task")
    op.drop_table("periodic_task")
    # ### end Alembic commands ###
