import os

import dotenv

dotenv.load_dotenv()

# PostgreSQL
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_ENDPOINT = os.getenv("POSTGRES_ENDPOINT")
DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_ENDPOINT}:{POSTGRES_PORT}/{POSTGRES_DB}"  # noqa

# Redis Configuration
REDIS_MAIN_ENDPOINT = os.getenv("REDIS_MAIN_ENDPOINT")
REDIS_MAIN_PORT = os.getenv("REDIS_MAIN_PORT")
REDIS_MAIN_PASSWORD = os.getenv("REDIS_MAIN_PASSWORD")

# Celery Configuration
if REDIS_MAIN_PASSWORD:
    CELERY_MAIN_BROKER_URL = f"redis://:{REDIS_MAIN_PASSWORD}@{REDIS_MAIN_ENDPOINT}:{REDIS_MAIN_PORT}/0"
else:
    CELERY_MAIN_BROKER_URL = f"redis://{REDIS_MAIN_ENDPOINT}:{REDIS_MAIN_PORT}/0"

CELERY_MAIN_RESULT_BACKEND = CELERY_MAIN_BROKER_URL

# App Configuration
APP_ENV = os.getenv("APP_ENV", "production")
